"""add assessment_responses and assessment_results tables

Revision ID: af592a3efdcf
Revises: 27333b47266e
Create Date: 2026-08-31 01:03:23.006117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af592a3efdcf'
down_revision: Union[str, Sequence[str], None] = '27333b47266e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assessment_code', sa.String(), nullable=False),
    sa.Column('item_scores', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("assessment_code IN ('phq9', 'gad7')", name='ck_assessment_code'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_responses_user_id'), 'assessment_responses', ['user_id'], unique=False)
    op.create_table('assessment_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assessment_code', sa.String(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('severity_band', sa.String(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['assessment_responses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id')
    )
    op.create_index(op.f('ix_assessment_results_user_id'), 'assessment_results', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_results_user_id'), table_name='assessment_results')
    op.drop_table('assessment_results')
    op.drop_index(op.f('ix_assessment_responses_user_id'), table_name='assessment_responses')
    op.drop_table('assessment_responses')
    # ### end Alembic commands ###
